version: "3.9"
services:
  db:
    image: "postgres:latest"
    ports:
      - "54320:5432"
    volumes:
      - ./devdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=eli
      - POSTGRES_PASSWORD=thisisme
      - POSTGRES_DB=elilevit
